sneaker/bake/urls.py
from django.conf.urls import url
from bake import views


urlpatterns = [
 url(r'^$', views.bake, name='bake'),
 
 ]

sneaker/main/urls.py
from django.conf.urls import url
from main import views


urlpatterns = [
 url(r'^$', views.main, name='main'),
 ]

sneaker/sneaker/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^track/', include('track.urls', namespace='track')),
    url(r'^deeds/', include('deeds.urls', namespace='deeds')),
    url(r'^bake/', include('bake.urls', namespace='bake')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^.*', include('main.urls')),
]

sneaker/wiki/urls.py
from django.conf.urls import url
from wiki import views
urlpatterns = [
        url(r'^$', views.wiki, name='wiki'),
        url(r'^category/(?P<categoryID>[0-9]+)/$', views.category, name='category'),
        url(r'^addCategory/$', views.addCategory, name='addCategory'),
        url(r'^addPage/(?P<categoryID>[0-9]+)/$', views.addPage, name='addPage'),
        url(r'^deleteCategory/(?P<categoryID>[0-9]+)/$', views.deleteCategory, name='deleteCategory'),
        url(r'^deletePage/(?P<pageID>[0-9]+)/$', views.deletePage, name='deletePage'),
        url(r'^updateCategory/(?P<categoryID>[0-9]+)/$', views.updateCategory, name='updateCategory'),
        url(r'^updatePage/(?P<pageID>[0-9]+)/$', views.updatePage, name='updatePage'),
]

sneaker/wiki/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
 
    def __str__(self):
        return self.name
    
    
    class Meta:
        ordering = ('-likes',)
        
        
class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128, unique=True)
    url = models.URLField()
    views = models.IntegerField(default=0)
    def __str__(self):
        return self.title
    
    
    class Meta:
        ordering = ('-views',)

sneaker/wiki/forms.py
from django import forms
from wiki.models import Category, Page


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, label='分類名稱', help_text='(請輸入分類名稱)')
 
    class Meta:
        model = Category
        fields = ('name', )
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, label='網頁標題')
    url = forms.URLField(max_length=128, label='網頁網址')
 
    class Meta:
        model = Page
        exclude = ('category', 'views')
        
        
    def clean(self):
        cleanedData = self.cleaned_data
        url = cleanedData.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleanedData['url'] = url
            return cleanedData
        
        
class NameForm(forms.Form):
    name = forms.CharField(max_length=100, label='姓名')

sneaker/wiki/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required 
from wiki.models import Category, Page
from wiki.forms import CategoryForm, PageForm


def wiki(request):
    categories = Category.objects.all()
    context = {'categories':categories}
    return render(request, 'wiki/wiki.html', context)


def category(request, categoryID):
    context = {}
    try:
        category = Category.objects.get(id=categoryID)
        context['category'] = category
        context['pages'] = Page.objects.filter(category=category)
    except Category.DoesNotExist:
        pass
    return render(request, 'wiki/category.html', context)

@login_required
def addCategory(request):
    template = 'wiki/addCategory.html'
    if request.method=='GET':
        return render(request, template, {'form':CategoryForm()})
    # request.method=='POST'
    form = CategoryForm(request.POST)
    if not form.is_valid():
        return render(request, template, {'form':form})
    form.save()
    return redirect(reverse('wiki:wiki'))
    # Or try this: return wiki(request) 

@login_required
def addPage(request, categoryID):
    template = 'wiki/addPage.html'
    try:
        pageCategory = Category.objects.get(id=categoryID)
    except Category.DoesNotExist:
        return category(request, categoryID)
    context = {'category':pageCategory}
    if request.method=='GET':
        context['form'] = PageForm()
        return render(request, template, context)
    # request.method=='POST'
    form = PageForm(request.POST)
    context['form'] = form
    if not form.is_valid():
        return render(request, template, context)
    page = form.save(commit=False)
    page.category = pageCategory
    page.save()
    return redirect(reverse('wiki:category', args=(categoryID, )))

@login_required
def deleteCategory(request, categoryID):
    if request.method!='POST':
        return wiki(request)
    # request.method=='POST':
    categoryToDelete = Category.objects.get(id=categoryID)
    if categoryToDelete:
        categoryToDelete.delete()
    return redirect(reverse('wiki:wiki'))  

@login_required
def deletePage(request, pageID):
    if request.method!='POST':
        return wiki(request)
    # request.method=='POST':
    pageToDelete = Page.objects.get(id=pageID)
    if pageToDelete:
        categoryID = pageToDelete.category.id
        pageToDelete.delete()
    else:
        categoryID = ''
    return redirect(reverse('wiki:category', args=(categoryID, )))

@login_required
def updateCategory(request, categoryID):
    template = 'wiki/updateCategory.html'
    try:
        category = Category.objects.get(id=categoryID)
    except Category.DoesNotExist:
        return wiki(request)
    if request.method=='GET':
        form = CategoryForm(instance=category)
        return render(request, template, {'form':form, 'category':category})
    # request.method=='POST'
    form = CategoryForm(request.POST, instance=category)
    if not form.is_valid():
        return render(request, template, {'form':form, 'category':category})
    form.save()
    return redirect(reverse('wiki:wiki'))

@login_required
def updatePage(request, pageID):
    template = 'wiki/updatePage.html'
    try:
        page = Page.objects.get(id=pageID)
    except Page.DoesNotExist:
        return category(request, '')
    if request.method=='GET':
        form = PageForm(instance=page)
        return render(request, template, {'form':form, 'page':page})
    # request.method=='POST'
    form = PageForm(request.POST, instance=page)
    if not form.is_valid():
        return render(request, template, {'form':form, 'page':page})
    form.save()
    return redirect(reverse('wiki:category', args=(page.category.id,)))

sneaker/wiki/templates/wiki/addCategory.html
{% extends 'main/main.html' %}
{% block content %}
{% load staticfiles %}
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>新增程式語言分類</h1>
<form method=post action={% url 'wiki:addCategory' %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<br>
<p><a href={% url 'wiki:wiki' %}>回餐廳美食目錄</a></p>
</body>
</html>
{% endblock %}

sneaker/wiki/templates/wiki/addPage.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>在"{{category.name}}"分類中新增一筆網頁</h1>
<form method=post action={% url 'wiki:addPage' category.id %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:category' category.id %}>回{{category.name}}網頁
</a></p>
</body>
</html>

sneaker/wiki/templates/wiki/category.html
{% extends 'main/main.html' %}
{% block content %}
{% load staticfiles %}
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>食譜推薦</title>
<meta charset=utf-8>
<link rel=stylesheet href="{% static 'main/css/main.css' %}">
</head>
<body>

{% if category %}
 <h1>{{category.name}}</h1>
 {% if pages %}
 <table>
 <tr><th>食譜推薦</th></tr>
 {% for page in pages %}
 <tr>
 <td>
 <a href={{page.url}}>{{page.title}}</a>
 </td>
 <td>
 {% if user.is_authenticated %}
 <form action={% url 'wiki:updatePage' page.id %}>
 <input type=submit value=修改>
 </form>
 {% endif %}
 </td>
 <td>
 {% if user.is_authenticated %}
 <form method=post action={% url 'wiki:deletePage' page.id %}>
 {% csrf_token %}
 <input type=submit value=刪除>
 </form>
 {% endif %}
 </td> 
 </tr>
 {% endfor %}
 </table>
 {% else %}
 <p><strong>此分類目前並無網頁。</strong></p>
 {% endif %}
 <br>
 {% if user.is_authenticated %}
 <p><a href={% url 'wiki:addPage' category.id %}>新增網頁</a></p>
 {% endif %} 
{% else %}
 <p>所指定的分類「{{categoryID}}」不存在。</p>
{% endif %}
&nbsp;&nbsp;&nbsp;&nbsp;
<p><a href={% url 'wiki:wiki' %}>回餐廳美食網頁</a></p>

</body>
</html>
{% endblock %}

sneaker/wiki/templates/wiki/updateCategory.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>修改程式語言分類</h1>
<form method=post action={% url 'wiki:updateCategory' category.id %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:wiki' %}>回 Wiki 網頁</a></p>
</body>
</html>

sneaker/wiki/templates/wiki/updatePage.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<!-- 一再撰寫相同的 HTML 標頭資料，有沒有人開始覺得很煩了？？ -->
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>修改網頁</h1>
<form method=post action={% url 'wiki:updatePage' page.id %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:category' page.category.id %}>回「{{page.category.name}}」網頁
</a></p>
</body>
</html>

sneaker/wiki/templates/wiki/wiki.html
{% extends 'main/main.html' %}
{% block content %}
{% load staticfiles %}
<!doctype html>
{% load staticfiles %}
<html>
<head>
</head>
<body>
{% if categories %}
 <h2>餐廳美食分類：</h2>
 <table>
 <tr><th>分類名稱</th><th></th><th></th></tr>
 {% for category in categories %}
 <tr>
 <td>
 {% if user.is_authenticated %}
 <a href={% url 'wiki:category' category.id %}>{{category.name}}</a>
 {% endif %}
 </td>
 <td>
 {% if user.is_authenticated %} 
 <form action={% url 'wiki:updateCategory' category.id %}>
 <input type="submit" value=修改>
 </form>
 {% endif %}
 </td>
 <td>
 {% if user.is_authenticated %} 
 <form method=post action={% url 'wiki:deleteCategory' category.id %}>
 <input type=submit value=刪除>
 {% csrf_token %}
  {% endif %}
 </form>
 </td>
 </tr>
 {% endfor %}
 </table>
{% else %}
 <p><strong>目前尚未設定程式語言分類。</strong></p>
{% endif %}
&nbsp;&nbsp;&nbsp;&nbsp;
<p><a href={% url 'wiki:addCategory' %}>新增美食</a></p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<p><a href={% url 'main:main' %}>回首頁</a></p>
</body>
</html>
{% endblock %}