sneaker/bake/urls.py
from django.conf.urls import url
from bake import views


urlpatterns = [
 url(r'^$', views.bake, name='bake'),
 
 ]

sneaker/sneaker/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^track/', include('track.urls', namespace='track')),
    url(r'^deeds/', include('deeds.urls', namespace='deeds')),
    url(r'^bake/', include('bake.urls', namespace='bake')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^.*', include('main.urls')),
]

sneaker/wiki/urls.py
from django.conf.urls import url
from wiki import views
urlpatterns = [
        url(r'^$', views.wiki, name='wiki'),
        url(r'^category/(?P<categoryID>[0-9]+)/$', views.category, name='category'),
        url(r'^addCategory/$', views.addCategory, name='addCategory'),
        url(r'^addPage/(?P<categoryID>[0-9]+)/$', views.addPage, name='addPage'),
        url(r'^deleteCategory/(?P<categoryID>[0-9]+)/$', views.deleteCategory, name='deleteCategory'),
        url(r'^deletePage/(?P<pageID>[0-9]+)/$', views.deletePage, name='deletePage'),
        url(r'^updateCategory/(?P<categoryID>[0-9]+)/$', views.updateCategory, name='updateCategory'),
        url(r'^updatePage/(?P<pageID>[0-9]+)/$', views.updatePage, name='updatePage'),
]

sneaker/bake/models.py
from django.db import models

# Create your models here.

sneaker/bake/views.py
from django.shortcuts import render


def bake(request):
    return render(request, 'bake/bake.html')

sneaker/bake/templates/bake/bake.html
{% extends 'main/main.html' %}
{% block content %}
{% load staticfiles %}
<h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href={% url 'wiki:wiki' %}>餐廳美食目錄</a></h1></p>
<p></p>
</p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src={% static 'bake/img/bake2.jpg' %} alt=餐廳美食></p>
<br>
{% endblock %}